version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/" # This should be / rather than .github/workflows
    schedule:
      interval: "daily"
    groups:
      github-actions-all:
        patterns:
          - "*"
    commit-message:
      prefix: ci(deps)

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    groups:
      gomod-all:
        patterns:
          - "*"
    commit-message:
      prefix: deps

  - package-ecosystem: npm
    directory: "docs-optimizer"
    schedule:
      interval: weekly
    groups:
      npm-all:
        patterns:
          - "*"
    commit-message:
      prefix: ci(deps)
