# The changelog is managed by release-please
changelog:
  disable: true

builds:
  - binary: ok
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

brews:
  - name: ok
    description: A CLI called ok
    homepage: https://github.com/oslokommune/ok
    goarm: 6
    goamd64: v1
    repository:
      owner: oslokommune
      name: ok
    directory: Formula
    install: |
      bin.install "ok"
