FROM archlinux:latest

RUN pacman -Sy --noconfirm gh

RUN TEMP_DIR=$(mktemp -d) && \
    gh release download --repo "oslokommune/ok" --pattern "*amd64.pkg.tar.zst" --dir "$TEMP_DIR" && \
    pacman -U --noconfirm "$TEMP_DIR"/*amd64.pkg.tar.zst && \
    rm -rf "$TEMP_DIR"

CMD ["ok"]
