FROM archlinux:latest

RUN pacman -Sy --noconfirm github-cli

RUN --mount=type=secret,id=github_token \
    export GITHUB_TOKEN=$(cat /run/secrets/github_token) && \
    TEMP_DIR=$(mktemp -d) && \
    gh release download --repo "oslokommune/ok" --pattern "*amd64.pkg.tar.zst" --dir "$TEMP_DIR" && \
    pacman -U --noconfirm "$TEMP_DIR"/*amd64.pkg.tar.zst && \
    rm -rf "$TEMP_DIR"

CMD ["ok"]
