Require ok

Output interactive.webm

Set FontSize 18
Set Width 1600
Set Height 900
Set Framerate 24

Set TypingSpeed 100ms

Type "eza --tree **.yml config/"
Sleep 3s
Enter
Sleep 3s

Type "ok pkg install --interactive"
Sleep 3s
Enter
Sleep 3s

Down@500ms
Down@500ms
Down@1s

Up@500ms
Up@500ms
Up@1s

Sleep 3s

Type "x"

Down@500ms
Down@500ms
Down@1s

Sleep 1s

Type "x"
Sleep 5s
Enter

Sleep 13s

Type "eza --tree out/"
Sleep 3s
Enter
Sleep 3s
