# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A CLI called ok"
  homepage "https://github.com/oslokommune/ok"
  version "1.25.0"

  on_macos do
    on_intel do
      url "https://github.com/oslokommune/ok/releases/download/v1.25.0/ok_1.25.0_darwin_amd64.tar.gz"
      sha256 "23cd4698803581f812bb1e083d3843b498f62e5a5e6e9c7e0b8dbfa33b5c6c98"

      def install
        bin.install "ok"
      end
    end
    on_arm do
      url "https://github.com/oslokommune/ok/releases/download/v1.25.0/ok_1.25.0_darwin_arm64.tar.gz"
      sha256 "f76c9d6a2e1fa9c54788cb6d04e721c4702fa9cd0e3c8a9ee3c89f42f612d764"

      def install
        bin.install "ok"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oslokommune/ok/releases/download/v1.25.0/ok_1.25.0_linux_amd64.tar.gz"
        sha256 "c18ff82a21f718be07360e7ef607abe1903bdf520a9a2fb11290b1e16043f0ca"

        def install
          bin.install "ok"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oslokommune/ok/releases/download/v1.25.0/ok_1.25.0_linux_arm64.tar.gz"
        sha256 "5f98443c7730ab1e541feed32bd4877ba743b4c60edd01a97aa7adff564971bf"

        def install
          bin.install "ok"
        end
      end
    end
  end
end
