# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A CLI called ok"
  homepage "https://github.com/oslokommune/ok"
  version "4.4.1"

  on_macos do
    on_intel do
      url "https://github.com/oslokommune/ok/releases/download/v4.4.1/ok_4.4.1_darwin_amd64.tar.gz"
      sha256 "39ed82a52c18dc785f85493838780040bcf79e021487e069f970d924df2de7c7"

      def install
        bin.install "ok"
        bash_completion.install "completions/ok.bash" => "ok"
        zsh_completion.install "completions/ok.zsh" => "_ok"
        fish_completion.install "completions/ok.fish"
      end
    end
    on_arm do
      url "https://github.com/oslokommune/ok/releases/download/v4.4.1/ok_4.4.1_darwin_arm64.tar.gz"
      sha256 "5d54e859bd173c32f769268f70e2386f7802a52cff4c1d325f900fd9682547d7"

      def install
        bin.install "ok"
        bash_completion.install "completions/ok.bash" => "ok"
        zsh_completion.install "completions/ok.zsh" => "_ok"
        fish_completion.install "completions/ok.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oslokommune/ok/releases/download/v4.4.1/ok_4.4.1_linux_amd64.tar.gz"
        sha256 "0d93f1d519f6ca8d140e640fff60a93a37f6c3b517d6a021b323d8296c76d46c"

        def install
          bin.install "ok"
          bash_completion.install "completions/ok.bash" => "ok"
          zsh_completion.install "completions/ok.zsh" => "_ok"
          fish_completion.install "completions/ok.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/oslokommune/ok/releases/download/v4.4.1/ok_4.4.1_linux_arm64.tar.gz"
        sha256 "72882eae28eee091fbf2cd9932b3a1d062c39b200fdaaa5d64e813c2bf085bb5"

        def install
          bin.install "ok"
          bash_completion.install "completions/ok.bash" => "ok"
          zsh_completion.install "completions/ok.zsh" => "_ok"
          fish_completion.install "completions/ok.fish"
        end
      end
    end
  end
end
