main: ok-pkg-update-auto-migrate-config.vhs
	git checkout -- packages.yml && git co -- config/app-hello.yml
	vhs ok-pkg-update-auto-migrate-config.vhs
	open ok-pkg-update-auto-migrate-config.webm
	git checkout -- packages.yml && git co -- config/app-hello.yml
