# yaml-language-server: $schema=.schemas/app-v9.3.3.schema.json
StackName: "app-hello"
app-data.StackName: "app-hello-data"
AppName: "hello"
AppEcsExec: true
AppReadOnlyRootFileSystem: true
ExampleImage:
  Enable: true
ServiceConnect:
  Enable: true
AlbHostRouting:
  Enable: true
  Internal: false
  Subdomain:
    Enable: true
    TargetGroupTargetStickiness: false
  ApexDomain:
    Enable: false
    TargetGroupTargetStickiness: false
DatabaseConnectivity:
  Enable: true
OpenTelemetrySidecar:
  Enable: true
VpcEndpoints:
  Enable: true
Xray:
  Enable: true
DailyShutdown:
  Enable: true
IamForCicd:
  Enable: true
  AppGitHubRepo: pirates-apps
  IacGitHubRepo: pirates-iac
  AssumableCdRole: false
