name: Test

on:
  pull_request: {}
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1


      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "go.sum"


      # We don't need the ok binary from the setup-ok action, but we need the dependencies.
      - name: Install ok dependencies
        uses: oslokommune/composite-actions/setup-ok@6054e3b0e9d06f15d19d9b6885a0c0e1a58ae9c7 # setup-ok: v1.6.3


      - name: Run tests
        uses: magefile/mage-action@a662bd8c29d8106879588cfff83b2faf6e6f59db # v4.0.0
        with:
          version: "v1.14.0"
          args: "test"
